spring:
  application:
    name: umc-pos-api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: bootstrap
          uri: lb://umc-pos-bootstrap-service
          predicates:
            - Path=/api/v1/bootstrap/**
        - id: auth
          uri: lb://umc-pos-auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user
          uri: lb://umc-pos-user-service
          predicates:
            - Path=/api/v1/user/**
        - id: role
          uri: lb://umc-pos-user-service
          predicates:
            - Path=/api/v1/role/**
        - id: accessControlList
          uri: lb://umc-pos-user-service
          predicates:
            - Path=/api/v1/acl/**
        - id: site
          uri: lb://umc-pos-business-unit-service
          predicates:
            - Path=/api/v1/site/**
        - id: retailer
          uri: lb://umc-pos-business-unit-service
          predicates:
            - Path=/api/v1/retailer/**
        - id: business-unit-group
          uri: lb://umc-pos-business-unit-service
          predicates:
            - Path=/api/v1/group/**

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
