spring:
  application:
    name: umc-pos-api-gateway-service
  cloud:
    gateway:
      routes:
        - id: bootstrap
          uri: lb://umc-pos-bootstrap-service
          predicates:
            - Path=/bootstrap/**

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
