spring:
  application:
    name: umc-pos-employee-service
  data:
    mongodb:
      host: ${MONGO_SERVER_IP:127.0.0.1}
      port: ${MONGO_SERVER_PORT:27017}
  jackson:
    date-format: "YYYY-MM-dd"
    time-zone: Europe/Paris
    locale: fr_FR
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL

server:
  port: 26025

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true