spring:
  application:
    name: umc-pos-price-service
  data:
    mongodb:
      host: ${MONGO_SERVER_IP:127.0.0.1}
      port: ${MONGO_SERVER_PORT:27017}
      database: umc_pos_db
      auto-index-creation: true
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL

spring.rabbitmq:
  host: ${RABBITMQ_SERVER_IP:127.0.0.1}
  port: ${RABBITMQ_SERVER_PORT:5672}
  username: guest
  password: guest

spring.cloud.stream:
  default:
    binder: rabbit
    contentType: application/json
  bindings:
    # Use the consumer function name as input to create destination and group
    itemConsumer-in-0:
      destination: umc-pos.item.events
      group: umc-pos.item-group
  # Consumer input binding parameters
  bindings.itemConsumer-in-0.consumer:
    maxAttempts: 3
    backOffInitialInterval: 500
    backOffMaxInterval: 1000
    backOffMultiplier: 2.0
  # RabbitMQ consumer input binding parameters
  rabbit.bindings.itemConsumer-in-0.consumer:
    autoBindDlq: true
    republishToDlq: true

jwt:
  secret: jeanvaljean

server:
  port: 26008

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    org.springframework:
      amqp:DEBUG

