spring:
  application:
    name: umc-pos-auth-service
  data:
    mongodb:
      host: ${MONGO_SERVER_IP:127.0.0.1}
      port: ${MONGO_SERVER_PORT:27017}
      database: umc_pos_auth
      auto-index-creation: true
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL

jwt:
  secret: jeanvaljean
  expiration: 600   # 10 minutes
  authHeader: Authorization

server:
  port: 26001

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: DEBUG
    org.springframework:
      amqp: INFO
