spring:
  application:
    name: umc-pos-api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: bootstrap
          uri: lb://umc-pos-bootstrap-service
          predicates:
            - Path=/api/v1/bootstrap/**
        - id: auth-service
          uri: lb://umc-pos-auth-service
          predicates:
            - Path=/auth/api/v1/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://umc-pos-user-service
          predicates:
            - Path=/user/api/v1/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: business-unit-service
          uri: lb://umc-pos-business-unit-service
          predicates:
            - Path=/business-unit/api/v1/**
          filters:
            - RewritePath=/business-unit/(?<path>.*), /$\{path}
        - id: customer-service
          uri: lb://umc-pos-customer-service
          predicates:
            - Path=/customer/api/v1/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
        - id: catalog-service
          uri: lb://umc-pos-catalog-service
          predicates:
            - Path=/catalog/api/v1/**
          filters:
            - RewritePath=/catalog/(?<path>.*), /$\{path}
        - id: location-service
          uri: lb://umc-pos-location-service
          predicates:
            - Path=/location/api/v1/**
          filters:
            - RewritePath=/location/(?<path>.*), /$\{path}
        - id: workstation-service
          uri: lb://umc-pos-workstation-service
          predicates:
            - Path=/workstation/api/v1/**
          filters:
            - RewritePath=/workstation/(?<path>.*), /$\{path}
        - id: price-service
          uri: lb://umc-pos-price-service
          predicates:
            - Path=/price/api/v1/**
          filters:
            - RewritePath=/price/(?<path>.*), /$\{path}
        - id: workstation-composite-service
          uri: lb://umc-pos-workstation-composite-service
          predicates:
            - Path=/workstation-composite/api/v1/**
          filters:
            - RewritePath=/workstation-composite/(?<path>.*), /$\{path}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
