spring:
  application:
    name: umc-pos-catalog-service
  data:
    mongodb:
      host: ${MONGO_SERVER_IP:127.0.0.1}
      port: ${MONGO_SERVER_PORT:27017}
      auto-index-creation: true
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL

server:
  port: 26024

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

feign:
  category:
    service: umc-pos-catalog-service
    url: "http://192.168.1.65:8765/catalog/api/v1"
  client:
    config:
      umc-pos-catalog-service:
        connectTimeout: 5000
        readTimeout: 5000

umc:
  tasks:
    updateCategoryPath:
      cron: "0 0/5 * * * ?"
    updateItemCategory:
      cron: "0 0/5 * * * ?"