spring:
  application:
    name: umc-pos-edge-service

server:
  port: 8765

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    umc-pos-discovery-service:
      path: /umc-pos-discovery-service/**
      sensitive-headers: SetCookie,Authorization
      url: http://localhost:8761
    umc-pos-ping-service:
      path: /ping/**
      sensitive-headers: SetCookie,Authorization
      serviceId: umc-pos-ping-service
    umc-pos-customer-service:
      path: /customers/**
      sensitive-headers: SetCookie,Authorization
      serviceId: umc-pos-customer-service
    umc-pos-store-service:
      path: /stores/**
      sensitive-headers: SetCookie,Authorization
      serviceId: umc-pos-store-service
    umc-pos-store-service:
      path: /users/**
      sensitive-headers: SetCookie,Authorization
      serviceId: umc-pos-user-service

histrix:
  command:
    umc-pos-discovery-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    umc-pos-ping-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

      